networks:
  traefik-proxy:
    external: true

volumes:
  certificates:
    external: true

services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.toml:/traefik.toml:ro
      - ./config/certificates/acme.json:/acme.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.middlewares.traefik-dashboard-auth.basicauth.users=admin:$$apr1$$Uazqzaux$$YDT/IZif09rWWybKr.QCg0"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-dashboard-auth@docker"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"