networks:
  traefik-proxy:
    external: true

volumes:
  certificates:
    external: true

services:
  traefik:
    image: traefik:v3.4
    command: 
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy"
      - "--certificatesResolvers.lets-encrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.lets-encrypt.acme.email=${DOMAIN_EMAIL}"
      - "--certificatesResolvers.lets-encrypt.acme.storage=/acme.json"
      - "--certificatesResolvers.lets-encrypt.acme.tlsChallenge=true"
      - "--serverstransport.insecureSkipVerify=true"
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/certificates/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.middlewares.traefik-dashboard-auth.basicauth.users=admin:$$apr1$$Uazqzaux$$YDT/IZif09rWWybKr.QCg0"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-dashboard-auth@docker"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"