entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  lets-encrypt:
    acme:
      email: heiwa.gabriel@gmail.com
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web