[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

  [traefik]
    address = ":8080"

[api]
  insecure = true
  dashboard = true

[log]
  level = "DEBUG"

[providers]
  [providers.docker]
    network = "traefik-proxy"
    exposedByDefault = false

[certificatesResolvers]
  [certificatesResolvers.lets-encrypt.acme]
    caServer = "https://acme-v02.api.letsencrypt.org/directory"
    email = "heiwa.gabriel@gmail.com"
    storage = "/certificates/acme.json"
    [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[serversTransport]
  insecureSkipVerify = true